// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/light.tsx";
import * as $4 from "./routes/manual.tsx";
import * as $5 from "./routes/movie.tsx";
import * as $6 from "./routes/project.tsx";
import * as $7 from "./routes/song.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/LightSlider.tsx";
import * as $$2 from "./islands/LightToggle.tsx";
import * as $$3 from "./islands/Manual.tsx";
import * as $$4 from "./islands/Movieh.tsx";
import * as $$5 from "./islands/Project.tsx";
import * as $$6 from "./islands/Songh.tsx";
import * as $$7 from "./islands/VideoPlayer.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/light.tsx": $3,
    "./routes/manual.tsx": $4,
    "./routes/movie.tsx": $5,
    "./routes/project.tsx": $6,
    "./routes/song.tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/LightSlider.tsx": $$1,
    "./islands/LightToggle.tsx": $$2,
    "./islands/Manual.tsx": $$3,
    "./islands/Movieh.tsx": $$4,
    "./islands/Project.tsx": $$5,
    "./islands/Songh.tsx": $$6,
    "./islands/VideoPlayer.tsx": $$7,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
